# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Baldwin' do
  use_frameworks!

  # Pods for Baldwin
  pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
  pod 'Alamofire'

  target 'BaldwinTests' do
    pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
  end

end
